"""Add optimization models

Revision ID: 016903748bb0
Revises: 5dd082dec6a9
Create Date: 2026-08-27 22:10:33.551412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '016903748bb0'
down_revision: Union[str, None] = '5dd082dec6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_runs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(length=50), nullable=False),
    sa.Column('risk_weight', sa.Float(), nullable=False),
    sa.Column('financial_weight', sa.Float(), nullable=False),
    sa.Column('criticality_weight', sa.Float(), nullable=False),
    sa.Column('urgency_weight', sa.Float(), nullable=False),
    sa.Column('confidence_weight', sa.Float(), nullable=False),
    sa.Column('optimization_status', sa.String(length=50), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('remaining_budget', sa.Float(), nullable=False),
    sa.Column('risk_before', sa.Float(), nullable=True),
    sa.Column('risk_after', sa.Float(), nullable=True),
    sa.Column('risk_reduction', sa.Float(), nullable=True),
    sa.Column('financial_before', sa.Float(), nullable=True),
    sa.Column('financial_after', sa.Float(), nullable=True),
    sa.Column('financial_reduction', sa.Float(), nullable=True),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('calculation_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_organization_id'), 'optimization_runs', ['organization_id'], unique=False)
    op.create_table('optimization_portfolios',
    sa.Column('optimization_run_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('selected_investments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('risk_reduction', sa.Float(), nullable=True),
    sa.Column('financial_reduction', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_portfolios_optimization_run_id'), 'optimization_portfolios', ['optimization_run_id'], unique=False)
    op.create_table('cybersecurity_investments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('cost_type', sa.String(length=50), nullable=False),
    sa.Column('annualized_cost', sa.Float(), nullable=True),
    sa.Column('implementation_effort', sa.String(length=50), nullable=True),
    sa.Column('risk_reduction', sa.Float(), nullable=True),
    sa.Column('financial_reduction', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cybersecurity_investments_asset_id'), 'cybersecurity_investments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_cybersecurity_investments_organization_id'), 'cybersecurity_investments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cybersecurity_investments_recommendation_id'), 'cybersecurity_investments', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_cybersecurity_investments_status'), 'cybersecurity_investments', ['status'], unique=False)
    op.create_table('risk_scenarios',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('optimization_portfolio_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('investments_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_before', sa.Float(), nullable=True),
    sa.Column('risk_after', sa.Float(), nullable=True),
    sa.Column('financial_before', sa.Float(), nullable=True),
    sa.Column('financial_after', sa.Float(), nullable=True),
    sa.Column('scenario_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['optimization_portfolio_id'], ['optimization_portfolios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scenarios_organization_id'), 'risk_scenarios', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_simulations_asset_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_organization_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_scenario_type'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_security_investments_category'), table_name='security_investments')
    op.drop_index(op.f('ix_security_investments_organization_id'), table_name='security_investments')
    op.drop_index(op.f('ix_security_investments_status'), table_name='security_investments')
    op.drop_table('security_investments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_investments',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('expected_risk_reduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('implementation_time_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('cost >= 0::double precision', name=op.f('chk_investment_cost')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('security_investments_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('security_investments_pkey'))
    )
    op.create_index(op.f('ix_security_investments_status'), 'security_investments', ['status'], unique=False)
    op.create_index(op.f('ix_security_investments_organization_id'), 'security_investments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_investments_category'), 'security_investments', ['category'], unique=False)
    op.create_table('simulations',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scenario_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('simulations_asset_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('simulations_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('simulations_pkey'))
    )
    op.create_index(op.f('ix_simulations_scenario_type'), 'simulations', ['scenario_type'], unique=False)
    op.create_index(op.f('ix_simulations_organization_id'), 'simulations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_simulations_asset_id'), 'simulations', ['asset_id'], unique=False)
    op.drop_index(op.f('ix_risk_scenarios_organization_id'), table_name='risk_scenarios')
    op.drop_table('risk_scenarios')
    op.drop_index(op.f('ix_cybersecurity_investments_status'), table_name='cybersecurity_investments')
    op.drop_index(op.f('ix_cybersecurity_investments_recommendation_id'), table_name='cybersecurity_investments')
    op.drop_index(op.f('ix_cybersecurity_investments_organization_id'), table_name='cybersecurity_investments')
    op.drop_index(op.f('ix_cybersecurity_investments_asset_id'), table_name='cybersecurity_investments')
    op.drop_table('cybersecurity_investments')
    op.drop_index(op.f('ix_optimization_portfolios_optimization_run_id'), table_name='optimization_portfolios')
    op.drop_table('optimization_portfolios')
    op.drop_index(op.f('ix_optimization_runs_organization_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    # ### end Alembic commands ###
