"""add_compliance_models

Revision ID: 2d5fc09b64ae
Revises: 016903748bb0
Create Date: 2026-08-27 22:18:55.002579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d5fc09b64ae'
down_revision: Union[str, None] = '016903748bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop existing data to avoid NOT NULL violations during column addition
    op.execute("TRUNCATE TABLE compliance_frameworks CASCADE")
    op.execute("TRUNCATE TABLE security_controls CASCADE")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_requirements',
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.String(length=100), nullable=False),
    sa.Column('parent_requirement_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('applicability', sa.String(length=100), nullable=True),
    sa.Column('requirement_type', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_requirement_id'], ['compliance_requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_requirements_framework_id'), 'compliance_requirements', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_requirements_requirement_id'), 'compliance_requirements', ['requirement_id'], unique=False)
    op.create_table('compliance_applicability',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_applicability_organization_id'), 'compliance_applicability', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_applicability_requirement_id'), 'compliance_applicability', ['requirement_id'], unique=False)
    op.create_table('compliance_assessments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_completeness', sa.Float(), nullable=True),
    sa.Column('control_effectiveness', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('assessment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assessor', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('calculation_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_assessments_framework_id'), 'compliance_assessments', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_organization_id'), 'compliance_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_requirement_id'), 'compliance_assessments', ['requirement_id'], unique=False)
    op.create_table('compliance_control_mappings',
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('coverage_percentage', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('mapping_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['security_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_control_mappings_control_id'), 'compliance_control_mappings', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_control_mappings_framework_id'), 'compliance_control_mappings', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_control_mappings_requirement_id'), 'compliance_control_mappings', ['requirement_id'], unique=False)
    op.create_table('compliance_evidence',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['security_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_evidence_control_id'), 'compliance_evidence', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_organization_id'), 'compliance_evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_requirement_id'), 'compliance_evidence', ['requirement_id'], unique=False)
    op.create_table('compliance_exceptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('business_justification', sa.String(), nullable=False),
    sa.Column('risk_acceptance_reference', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['security_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_exceptions_control_id'), 'compliance_exceptions', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_exceptions_organization_id'), 'compliance_exceptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_exceptions_requirement_id'), 'compliance_exceptions', ['requirement_id'], unique=False)
    op.create_table('compliance_gaps',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('gap_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('financial_exposure', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('evidence_gap', sa.String(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['security_controls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_gaps_asset_id'), 'compliance_gaps', ['asset_id'], unique=False)
    op.create_index(op.f('ix_compliance_gaps_control_id'), 'compliance_gaps', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_gaps_framework_id'), 'compliance_gaps', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_gaps_organization_id'), 'compliance_gaps', ['organization_id'], unique=False)
    op.create_index(op.f('ix_compliance_gaps_requirement_id'), 'compliance_gaps', ['requirement_id'], unique=False)
    op.drop_index(op.f('ix_control_assessments_compliance_control_id'), table_name='control_assessments')
    op.drop_index(op.f('ix_control_assessments_organization_id'), table_name='control_assessments')
    op.drop_index(op.f('ix_control_assessments_status'), table_name='control_assessments')
    op.drop_table('control_assessments')
    op.drop_index(op.f('ix_compliance_controls_control_id'), table_name='compliance_controls')
    op.drop_index(op.f('ix_compliance_controls_framework_id'), table_name='compliance_controls')
    op.drop_table('compliance_controls')
    op.add_column('compliance_frameworks', sa.Column('jurisdiction', sa.String(length=100), nullable=True))
    op.add_column('compliance_frameworks', sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('compliance_frameworks', sa.Column('source_reference', sa.String(length=255), nullable=True))
    op.add_column('compliance_frameworks', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('compliance_frameworks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('compliance_frameworks', 'description')
    op.add_column('security_controls', sa.Column('implementation_status', sa.String(length=50), nullable=False))
    op.add_column('security_controls', sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_controls', 'next_review_at')
    op.drop_column('security_controls', 'implementation_status')
    op.add_column('compliance_frameworks', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('compliance_frameworks', 'updated_at')
    op.drop_column('compliance_frameworks', 'status')
    op.drop_column('compliance_frameworks', 'source_reference')
    op.drop_column('compliance_frameworks', 'effective_date')
    op.drop_column('compliance_frameworks', 'jurisdiction')
    op.create_table('compliance_controls',
    sa.Column('framework_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('control_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('requirement_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], name='compliance_controls_framework_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='compliance_controls_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_compliance_controls_framework_id'), 'compliance_controls', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_controls_control_id'), 'compliance_controls', ['control_id'], unique=False)
    op.create_table('control_assessments',
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('compliance_control_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('assessed_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['compliance_control_id'], ['compliance_controls.id'], name=op.f('control_assessments_compliance_control_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('control_assessments_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('control_assessments_pkey'))
    )
    op.create_index(op.f('ix_control_assessments_status'), 'control_assessments', ['status'], unique=False)
    op.create_index(op.f('ix_control_assessments_organization_id'), 'control_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_control_assessments_compliance_control_id'), 'control_assessments', ['compliance_control_id'], unique=False)
    op.drop_index(op.f('ix_compliance_gaps_requirement_id'), table_name='compliance_gaps')
    op.drop_index(op.f('ix_compliance_gaps_organization_id'), table_name='compliance_gaps')
    op.drop_index(op.f('ix_compliance_gaps_framework_id'), table_name='compliance_gaps')
    op.drop_index(op.f('ix_compliance_gaps_control_id'), table_name='compliance_gaps')
    op.drop_index(op.f('ix_compliance_gaps_asset_id'), table_name='compliance_gaps')
    op.drop_table('compliance_gaps')
    op.drop_index(op.f('ix_compliance_exceptions_requirement_id'), table_name='compliance_exceptions')
    op.drop_index(op.f('ix_compliance_exceptions_organization_id'), table_name='compliance_exceptions')
    op.drop_index(op.f('ix_compliance_exceptions_control_id'), table_name='compliance_exceptions')
    op.drop_table('compliance_exceptions')
    op.drop_index(op.f('ix_compliance_evidence_requirement_id'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_organization_id'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_control_id'), table_name='compliance_evidence')
    op.drop_table('compliance_evidence')
    op.drop_index(op.f('ix_compliance_control_mappings_requirement_id'), table_name='compliance_control_mappings')
    op.drop_index(op.f('ix_compliance_control_mappings_framework_id'), table_name='compliance_control_mappings')
    op.drop_index(op.f('ix_compliance_control_mappings_control_id'), table_name='compliance_control_mappings')
    op.drop_table('compliance_control_mappings')
    op.drop_index(op.f('ix_compliance_assessments_requirement_id'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_organization_id'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_framework_id'), table_name='compliance_assessments')
    op.drop_table('compliance_assessments')
    op.drop_index(op.f('ix_compliance_applicability_requirement_id'), table_name='compliance_applicability')
    op.drop_index(op.f('ix_compliance_applicability_organization_id'), table_name='compliance_applicability')
    op.drop_table('compliance_applicability')
    op.drop_index(op.f('ix_compliance_requirements_requirement_id'), table_name='compliance_requirements')
    op.drop_index(op.f('ix_compliance_requirements_framework_id'), table_name='compliance_requirements')
    op.drop_table('compliance_requirements')
    # ### end Alembic commands ###
