"""module5 threat intel models

Revision ID: 39a3c3a37c62
Revises: 5aac05dcedb8
Create Date: 2026-08-27 20:41:43.968224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39a3c3a37c62'
down_revision: Union[str, None] = '5aac05dcedb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_intelligence_records',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('intelligence_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('known_exploited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threat_intel_dedup', 'threat_intelligence_records', ['source', 'source_record_id'], unique=True)
    op.create_index(op.f('ix_threat_intelligence_records_intelligence_type'), 'threat_intelligence_records', ['intelligence_type'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_records_known_exploited'), 'threat_intelligence_records', ['known_exploited'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_records_severity'), 'threat_intelligence_records', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_records_source'), 'threat_intelligence_records', ['source'], unique=False)
    op.create_index(op.f('ix_threat_intelligence_records_source_record_id'), 'threat_intelligence_records', ['source_record_id'], unique=False)
    op.create_table('threat_indicators',
    sa.Column('threat_record_id', sa.UUID(), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['threat_record_id'], ['threat_intelligence_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threat_indicator_dedup', 'threat_indicators', ['indicator_type', 'value'], unique=True)
    op.create_index(op.f('ix_threat_indicators_active'), 'threat_indicators', ['active'], unique=False)
    op.create_index(op.f('ix_threat_indicators_indicator_type'), 'threat_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_indicators_threat_record_id'), 'threat_indicators', ['threat_record_id'], unique=False)
    op.create_index(op.f('ix_threat_indicators_value'), 'threat_indicators', ['value'], unique=False)
    op.create_table('threat_correlations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('threat_record_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('vulnerability_id', sa.UUID(), nullable=True),
    sa.Column('correlation_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_record_id'], ['threat_intelligence_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threat_corr_asset_dedup', 'threat_correlations', ['organization_id', 'threat_record_id', 'asset_id'], unique=True, postgresql_where='asset_id IS NOT NULL')
    op.create_index('ix_threat_corr_vuln_dedup', 'threat_correlations', ['organization_id', 'threat_record_id', 'vulnerability_id'], unique=True, postgresql_where='vulnerability_id IS NOT NULL')
    op.create_index(op.f('ix_threat_correlations_asset_id'), 'threat_correlations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_threat_correlations_organization_id'), 'threat_correlations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_threat_correlations_threat_record_id'), 'threat_correlations', ['threat_record_id'], unique=False)
    op.create_index(op.f('ix_threat_correlations_vulnerability_id'), 'threat_correlations', ['vulnerability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_correlations_vulnerability_id'), table_name='threat_correlations')
    op.drop_index(op.f('ix_threat_correlations_threat_record_id'), table_name='threat_correlations')
    op.drop_index(op.f('ix_threat_correlations_organization_id'), table_name='threat_correlations')
    op.drop_index(op.f('ix_threat_correlations_asset_id'), table_name='threat_correlations')
    op.drop_index('ix_threat_corr_vuln_dedup', table_name='threat_correlations', postgresql_where='vulnerability_id IS NOT NULL')
    op.drop_index('ix_threat_corr_asset_dedup', table_name='threat_correlations', postgresql_where='asset_id IS NOT NULL')
    op.drop_table('threat_correlations')
    op.drop_index(op.f('ix_threat_indicators_value'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_threat_record_id'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_indicator_type'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_active'), table_name='threat_indicators')
    op.drop_index('ix_threat_indicator_dedup', table_name='threat_indicators')
    op.drop_table('threat_indicators')
    op.drop_index(op.f('ix_threat_intelligence_records_source_record_id'), table_name='threat_intelligence_records')
    op.drop_index(op.f('ix_threat_intelligence_records_source'), table_name='threat_intelligence_records')
    op.drop_index(op.f('ix_threat_intelligence_records_severity'), table_name='threat_intelligence_records')
    op.drop_index(op.f('ix_threat_intelligence_records_known_exploited'), table_name='threat_intelligence_records')
    op.drop_index(op.f('ix_threat_intelligence_records_intelligence_type'), table_name='threat_intelligence_records')
    op.drop_index('ix_threat_intel_dedup', table_name='threat_intelligence_records')
    op.drop_table('threat_intelligence_records')
    # ### end Alembic commands ###
