"""add_dashboard_models

Revision ID: 44e039f49194
Revises: 2d5fc09b64ae
Create Date: 2026-08-27 22:27:25.694251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e039f49194'
down_revision: Union[str, None] = '2d5fc09b64ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_alerts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source_module', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('action_link', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_alerts_fingerprint'), 'dashboard_alerts', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_dashboard_alerts_organization_id'), 'dashboard_alerts', ['organization_id'], unique=False)
    op.create_table('executive_insights',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_insights_organization_id'), 'executive_insights', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executive_insights_organization_id'), table_name='executive_insights')
    op.drop_table('executive_insights')
    op.drop_index(op.f('ix_dashboard_alerts_organization_id'), table_name='dashboard_alerts')
    op.drop_index(op.f('ix_dashboard_alerts_fingerprint'), table_name='dashboard_alerts')
    op.drop_table('dashboard_alerts')
    # ### end Alembic commands ###
