"""module4 telemetry dedup index

Revision ID: 5aac05dcedb8
Revises: e1b8595d0e95
Create Date: 2026-08-27 20:25:39.475863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aac05dcedb8'
down_revision: Union[str, None] = 'e1b8595d0e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_telemetry_dedup', 'telemetry_events', ['organization_id', 'source', 'source_event_id'], unique=True, postgresql_where='source_event_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_dedup', table_name='telemetry_events', postgresql_where='source_event_id IS NOT NULL')
    # ### end Alembic commands ###
