"""Add financial risk models

Revision ID: d8fe73c124ec
Revises: 39a3c3a37c62
Create Date: 2026-08-27 21:36:52.721788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8fe73c124ec'
down_revision: Union[str, None] = '39a3c3a37c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_assumptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='chk_financial_assumption_confidence'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_assumptions_category'), 'financial_assumptions', ['category'], unique=False)
    op.create_index(op.f('ix_financial_assumptions_organization_id'), 'financial_assumptions', ['organization_id'], unique=False)
    op.create_table('financial_risk_assessments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('potential_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('expected_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('annualized_expected_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('direct_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('data_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('business_interruption_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recovery_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('customer_impact', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('third_party_impact', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('regulatory_legal_exposure', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fraud_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reputation_revenue_impact', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('calculation_version', sa.String(length=50), nullable=False),
    sa.Column('assumptions_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='chk_financial_risk_confidence'),
    sa.CheckConstraint('expected_loss >= 0', name='chk_expected_loss'),
    sa.CheckConstraint('potential_loss >= 0', name='chk_potential_loss'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_risk_assessments_asset_id'), 'financial_risk_assessments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_financial_risk_assessments_calculated_at'), 'financial_risk_assessments', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_financial_risk_assessments_organization_id'), 'financial_risk_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_financial_risk_assessments_risk_score_id'), 'financial_risk_assessments', ['risk_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_risk_assessments_risk_score_id'), table_name='financial_risk_assessments')
    op.drop_index(op.f('ix_financial_risk_assessments_organization_id'), table_name='financial_risk_assessments')
    op.drop_index(op.f('ix_financial_risk_assessments_calculated_at'), table_name='financial_risk_assessments')
    op.drop_index(op.f('ix_financial_risk_assessments_asset_id'), table_name='financial_risk_assessments')
    op.drop_table('financial_risk_assessments')
    op.drop_index(op.f('ix_financial_assumptions_organization_id'), table_name='financial_assumptions')
    op.drop_index(op.f('ix_financial_assumptions_category'), table_name='financial_assumptions')
    op.drop_table('financial_assumptions')
    # ### end Alembic commands ###
