"""module2 models

Revision ID: e1b8595d0e95
Revises: 
Create Date: 2026-08-27 20:07:47.765247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1b8595d0e95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_frameworks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_frameworks_name'), 'compliance_frameworks', ['name'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('organization_type', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('assets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=100), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('business_value', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('technology', sa.String(length=255), nullable=True),
    sa.Column('internet_exposed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('business_value >= 0', name='chk_asset_business_value'),
    sa.CheckConstraint('criticality >= 0 AND criticality <= 100', name='chk_asset_criticality'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_internet_exposed'), 'assets', ['internet_exposed'], unique=False)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('compliance_controls',
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('requirement_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_controls_control_id'), 'compliance_controls', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_controls_framework_id'), 'compliance_controls', ['framework_id'], unique=False)
    op.create_table('security_controls',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('control_type', sa.String(length=100), nullable=False),
    sa.Column('coverage_percentage', sa.Float(), nullable=True),
    sa.Column('effectiveness_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('implementation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('coverage_percentage >= 0 AND coverage_percentage <= 100', name='chk_control_coverage'),
    sa.CheckConstraint('effectiveness_percentage >= 0 AND effectiveness_percentage <= 100', name='chk_control_effectiveness'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_controls_control_type'), 'security_controls', ['control_type'], unique=False)
    op.create_index(op.f('ix_security_controls_organization_id'), 'security_controls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_controls_status'), 'security_controls', ['status'], unique=False)
    op.create_table('security_investments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('expected_risk_reduction', sa.Float(), nullable=True),
    sa.Column('implementation_time_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost >= 0', name='chk_investment_cost'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_investments_category'), 'security_investments', ['category'], unique=False)
    op.create_index(op.f('ix_security_investments_organization_id'), 'security_investments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_security_investments_status'), 'security_investments', ['status'], unique=False)
    op.create_table('threats',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('threat_score >= 0 AND threat_score <= 100', name='chk_threat_score'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threats_active'), 'threats', ['active'], unique=False)
    op.create_index(op.f('ix_threats_organization_id'), 'threats', ['organization_id'], unique=False)
    op.create_index(op.f('ix_threats_severity'), 'threats', ['severity'], unique=False)
    op.create_index(op.f('ix_threats_threat_type'), 'threats', ['threat_type'], unique=False)
    op.create_table('control_assessments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('compliance_control_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['compliance_control_id'], ['compliance_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_assessments_compliance_control_id'), 'control_assessments', ['compliance_control_id'], unique=False)
    op.create_index(op.f('ix_control_assessments_organization_id'), 'control_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_control_assessments_status'), 'control_assessments', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('expected_risk_reduction', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_asset_id'), 'recommendations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_recommendations_organization_id'), 'recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('risk_scores',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('calculation_version', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='chk_risk_score'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_asset_id'), 'risk_scores', ['asset_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_calculated_at'), 'risk_scores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_organization_id'), 'risk_scores', ['organization_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_risk_level'), 'risk_scores', ['risk_level'], unique=False)
    op.create_table('simulations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scenario_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_asset_id'), 'simulations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_simulations_organization_id'), 'simulations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_simulations_scenario_type'), 'simulations', ['scenario_type'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_asset_id'), 'telemetry_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_event_type'), 'telemetry_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_telemetry_events_occurred_at'), 'telemetry_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_telemetry_events_organization_id'), 'telemetry_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_severity'), 'telemetry_events', ['severity'], unique=False)
    op.create_index(op.f('ix_telemetry_events_source'), 'telemetry_events', ['source'], unique=False)
    op.create_index(op.f('ix_telemetry_events_source_event_id'), 'telemetry_events', ['source_event_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('exploitability_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cvss_score >= 0 AND cvss_score <= 10.0', name='chk_vuln_cvss_score'),
    sa.CheckConstraint('exploitability_score >= 0 AND exploitability_score <= 10.0', name='chk_vuln_exploitability_score'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_asset_id'), 'vulnerabilities', ['asset_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_status'), 'vulnerabilities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_status'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_asset_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_telemetry_events_source_event_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_source'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_severity'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_organization_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_occurred_at'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_event_type'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_asset_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_simulations_scenario_type'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_organization_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_asset_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_risk_scores_risk_level'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_organization_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_calculated_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_asset_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_organization_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_asset_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_control_assessments_status'), table_name='control_assessments')
    op.drop_index(op.f('ix_control_assessments_organization_id'), table_name='control_assessments')
    op.drop_index(op.f('ix_control_assessments_compliance_control_id'), table_name='control_assessments')
    op.drop_table('control_assessments')
    op.drop_index(op.f('ix_threats_threat_type'), table_name='threats')
    op.drop_index(op.f('ix_threats_severity'), table_name='threats')
    op.drop_index(op.f('ix_threats_organization_id'), table_name='threats')
    op.drop_index(op.f('ix_threats_active'), table_name='threats')
    op.drop_table('threats')
    op.drop_index(op.f('ix_security_investments_status'), table_name='security_investments')
    op.drop_index(op.f('ix_security_investments_organization_id'), table_name='security_investments')
    op.drop_index(op.f('ix_security_investments_category'), table_name='security_investments')
    op.drop_table('security_investments')
    op.drop_index(op.f('ix_security_controls_status'), table_name='security_controls')
    op.drop_index(op.f('ix_security_controls_organization_id'), table_name='security_controls')
    op.drop_index(op.f('ix_security_controls_control_type'), table_name='security_controls')
    op.drop_table('security_controls')
    op.drop_index(op.f('ix_compliance_controls_framework_id'), table_name='compliance_controls')
    op.drop_index(op.f('ix_compliance_controls_control_id'), table_name='compliance_controls')
    op.drop_table('compliance_controls')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_internet_exposed'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_compliance_frameworks_name'), table_name='compliance_frameworks')
    op.drop_table('compliance_frameworks')
    # ### end Alembic commands ###
