import uuid
from typing import List
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import select, desc

from app.api.deps import get_db, get_current_user
from app.models.user import User
from app.models.optimization import OptimizationRun, CybersecurityInvestment
from app.schemas.optimization import OptimizationRunRead, OptimizationRunRequest, CybersecurityInvestmentRead
from app.services.optimization.engine import OptimizationEngine

router = APIRouter()

@router.post("/run", response_model=OptimizationRunRead)
def run_optimization(
    request: OptimizationRunRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Run the cybersecurity investment optimization engine.
    """
    engine = OptimizationEngine(db, current_user.organization_id)
    run = engine.run_optimization(request)
    
    # We return the run, including its portfolios relationship
    return run

@router.get("/runs", response_model=List[OptimizationRunRead])
def get_optimization_runs(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get all historical optimization runs for comparison.
    """
    runs = db.scalars(
        select(OptimizationRun)
        .where(OptimizationRun.organization_id == current_user.organization_id)
        .order_by(desc(OptimizationRun.created_at))
    ).all()
    return runs

@router.get("/investments", response_model=List[CybersecurityInvestmentRead])
def get_investment_candidates(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Get all candidate investments generated by the recommendation engine.
    """
    candidates = db.scalars(
        select(CybersecurityInvestment)
        .where(CybersecurityInvestment.organization_id == current_user.organization_id)
        .order_by(desc(CybersecurityInvestment.priority))
    ).all()
    return candidates
